title: Unsupervised Analysis Project
description: You can contact me via <a href="https://www.linkedin.com/in/batinkimberly/">LinkedIn</a> for collaboration or feedback. 
# logo: just in case i want to put photo
# description below image if there is
# from here: https://github.com/pages-themes/minimal?tab=readme-ov-file
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
